import test from 'node:test';
import assert from 'node:assert/strict';
import {quizPoints,writingPoints,validateGrade} from './grading.js';
import {questions,tasks} from './content.js';
import {handle,Quota} from './worker.js';
const good={content:10,lexis:12,grammar:9,design:12,contentReason:'Relevant.',lexisReason:'Varied.',grammarReason:'Mostly correct.',designReason:'Coherent.',strengths:['Klare Position.'],improvements:['Beispiel genauer erklären.'],corrections:[{original:'I has a plan.',suggestion:'I have a plan.',explanation:'Kongruenz.'}],nextStep:'Ein Beispiel ergänzen.'};
test('practice scale, endpoints and equal language weights',()=>{assert.equal(quizPoints(0,6),1);assert.equal(quizPoints(3,6),8);assert.equal(quizPoints(6,6),15);assert.equal(writingPoints(10,12,9,12).total,11);assert.equal(writingPoints(10,12,9,12).language,11);assert.equal(writingPoints(0,0,0,0).floorApplied,true);assert.throws(()=>validateGrade({...good,content:16}));assert.throws(()=>validateGrade({...good,lexis:5.5}));});
test('all quiz pools and task-source references are complete',()=>{assert.equal(Object.values(questions).flat().length,40);for(const pool of Object.values(questions)){assert.equal(pool.length,10);assert.equal(new Set(pool.map(q=>q.prompt)).size,10);for(const q of pool){assert.equal(q.options.length,3);assert.equal(new Set(q.options).size,3);assert.ok(q.options[q.correct]);assert.ok(q.explanation);}}assert.equal(new Set(tasks.map(t=>t.id)).size,6);});
const origin='https://herrhahn.github.io';
const env={ALLOWED_ORIGIN:origin,OPENAI_API_KEY:'test-key-only',OPENAI_MODEL:'test-model',ACCESS_CODES:'test-code-123456789',TEACHER_SECRET:'teacher-test-secret',RESULTS:{idFromName:x=>x,get:()=>({fetch:async()=>new Response(null,{status:201})})},QUOTA:{idFromName:x=>x,get:()=>({fetch:async()=>new Response(null,{status:204})})}};
function req(body={},opts={}){return new Request('https://example.test/grade',{method:opts.method||'POST',headers:{Origin:opts.origin||origin,Authorization:'Bearer '+(opts.code||'test-code-123456789'),'Content-Type':'application/json'},...(opts.method==='OPTIONS'?{}:{body:JSON.stringify({name:'Testperson',taskId:'point-maya',text:'I has a plan. This text discusses a gap year and how students can learn with a purpose.',...body})})});}
test('access, configuration and invalid submissions fail closed',async()=>{assert.equal((await handle(req(),{...env,OPENAI_API_KEY:''})).status,503);assert.equal((await handle(req({}, {code:'wrong'}),env)).status,401);assert.equal((await handle(req({}, {origin:'https://evil.test'}),env)).status,403);assert.equal((await handle(req({taskId:'invented'}),env)).status,400);assert.equal((await handle(req({text:'short'}),env)).status,400);assert.equal((await handle(req({text:'a'.repeat(40001)}),env)).status,400);const pre=await handle(req({}, {method:'OPTIONS'}),env);assert.equal(pre.status,204);assert.equal(pre.headers.get('Access-Control-Allow-Origin'),origin);});
test('model request uses trusted rubric and disabled storage; valid output accepted',async()=>{let seen;const r=await handle(req(),env,async(url,options)=>{seen=JSON.parse(options.body);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(good)}]}]});});assert.equal(r.status,200);assert.equal(seen.store,false);assert.match(seen.instructions,/IQB/);assert.equal(seen.text.format.strict,true);assert.ok(!JSON.stringify(seen).includes('test-code-123456789'));assert.equal((await r.json()).content,10);});
test('incomplete, invalid and upstream failures never produce fabricated marks',async()=>{assert.equal((await handle(req(),env,async()=>Response.json({status:'incomplete'}))).status,502);assert.equal((await handle(req(),env,async()=>new Response('',{status:429}))).status,502);assert.equal((await handle(req(),env,async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'garbage'}]}]}))).status,502);});
test('invented correction quotations are removed',async()=>{const g={...good,corrections:[{original:'never submitted',suggestion:'x',explanation:'x'}]};const r=await handle(req(),env,async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(g)}]}]}));assert.equal((await r.json()).corrections.length,0);});
test('durable quota blocks a repeated immediate call and caps daily total',async()=>{let ledger;const tx={get:async()=>ledger,put:async(k,v)=>{ledger=v;}};const state={storage:{transaction:async f=>f(tx),setAlarm:async()=>{},deleteAll:async()=>{ledger=undefined;}}};const quota=new Quota(state);const call=()=>quota.fetch(new Request('https://quota/check',{method:'POST',body:JSON.stringify({hash:'a'.repeat(64)})}));assert.equal((await call()).status,204);assert.equal((await call()).status,429);ledger.total=300;ledger.users={};assert.equal((await call()).status,429);await quota.alarm();assert.equal(ledger,undefined);});

import {Results,quizRecord,studentName} from './results.js';
test('teacher endpoints reject student access and names never reach OpenAI',async()=>{const request=new Request('https://example.test/teacher/results',{method:'POST',headers:{Origin:origin,Authorization:'Bearer test-code-123456789'}});assert.equal((await handle(request,env)).status,401);let seen;await handle(req(),env,async(u,o)=>{seen=o.body;return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(good)}]}]});});assert.ok(!seen.includes('Testperson'));assert.equal((await handle(req({name:''}),env)).status,400);});
test('quiz validates scores, duplicate attempts stay unique and expiry excludes rows',async()=>{assert.equal(studentName(' X '),'');assert.equal(quizRecord({name:'Test',module:'gap',total:6,correct:9,seconds:20,attemptId:'a'.repeat(20)},[{id:'gap'}]),null);const map=new Map();const tx={get:async k=>map.get(k),put:async(k,v)=>map.set(k,v)};const storage={...tx,getAlarm:async()=>null,transaction:async f=>f(tx),list:async(o={})=>new Map([...map].filter(([k])=>!o.prefix||k.startsWith(o.prefix))),setAlarm:async()=>{},delete:async ks=>ks.forEach(k=>map.delete(k))};const results=new Results({storage});const row={id:'test-attempt',date:new Date().toISOString(),name:'Test',points:8};const record=()=>results.fetch(new Request('https://results/record',{method:'POST',body:JSON.stringify(row)}));assert.equal((await record()).status,201);assert.equal((await record()).status,200);map.set('result:expired',{...row,date:'2020-01-01T00:00:00.000Z'});const data=await (await results.fetch(new Request('https://results/list'))).json();assert.equal(data.rows.length,1);await results.alarm();assert.equal(map.has('result:expired'),false);});
