export const modules = [
 {id:'gap',title:'Gap years',subtitle:'Chancen, Grenzen & gute Entscheidungen',time:'3 Min.',description:'Was bringt ein Gap Year wirklich? Wiederhole Argumente, Finanzierung und Erfahrungen aus der Einheit.'},
 {id:'point',title:'Point out',subtitle:'Kernaussagen auf den Punkt',time:'3 Min.',description:'Wähle relevante Informationen aus und fasse sie sachlich in eigenen Worten zusammen.'},
 {id:'analyse',title:'Basic analysis',subtitle:'Mittel erkennen. Wirkung erklären.',time:'4 Min.',description:'Direkte Ansprache, Wiederholung und Kontrast: kleine Werkzeuge mit großer Wirkung.'},
 {id:'speech',title:'Write a speech',subtitle:'Deine Position. Deine Stimme.',time:'3 Min.',description:'Baue überzeugende Argumente auf und sprich dein Publikum gezielt an.'}
];
export const lessons = {
gap:`<h2>A year out. A step forward?</h2><p>Ein Gap Year ist eine bewusst gestaltete Zeit zwischen zwei Ausbildungs- oder Lebensphasen, zum Beispiel nach der Schule. Es kann Freiwilligendienst, Arbeit, Reisen oder verschiedene Aktivitäten verbinden. Es muss weder ein ganzes Jahr dauern noch im Ausland stattfinden.</p><div class="grid two"><div class="card"><h3>Opportunities</h3><ul><li>Mehr Selbstständigkeit und Selbstvertrauen</li><li>Berufliche Orientierung und praktische Fähigkeiten</li><li>Sprachen lernen und andere Perspektiven kennenlernen</li><li>Mit sinnvollen Aufgaben zu einem Projekt beitragen</li></ul></div><div class="card"><h3>Challenges</h3><ul><li>Kosten und ungleiche finanzielle Möglichkeiten</li><li>Heimweh, Einsamkeit und Kulturschock</li><li>Verantwortung, Vorbereitung und Sicherheit</li><li>Ein späterer Studienbeginn ohne Garantie auf bessere Orientierung</li></ul></div></div><h2>Aus eurer Edumap</h2><p><strong>„Bühne statt Bürojob“:</strong> Ein FSJ Kultur kann praktische Einblicke und berufliche Orientierung ermöglichen. Die Beispiele zeigen aber auch: Alltag und Aufgaben unterscheiden sich; Geld und Unterkunft müssen geplant werden.</p><p><strong>„Paula hilft ein Jahr lang in Südafrika“:</strong> Freiwilligendienst verbindet Mitarbeit und interkulturelles Lernen. Vorbereitung, Finanzierung und ein realistischer Blick auf die eigenen Aufgaben gehören dazu. Finanzangaben in diesen älteren Artikeln beschreiben die damaligen Beispiele, keine aktuellen allgemeinen Fördersätze.</p><blockquote lang="en">A gap year can be valuable if it has a clear purpose and a realistic plan.</blockquote><h2>Build an argument</h2><p><span lang="en"><strong>Claim:</strong> A gap year can help students choose a career.<br><strong>Reason:</strong> They experience everyday work before committing to a course.<br><strong>Example:</strong> A volunteer at a theatre may discover an interest in event technology.<br><strong>Limit:</strong> This experience is useful, but it does not guarantee a job.</span></p><h3>Useful vocabulary</h3><p lang="en">volunteering · independence · work experience · career choices · homesickness · funding · accommodation · responsibility · local community</p>`,
point:`<h2>Point out ≠ deine Meinung abgeben</h2><p>Die Operatorenliste eurer Edumap verlangt, Informationen gezielt zusammenzutragen, ohne sie zu kommentieren. Entscheidend ist der Fokus der Aufgabenstellung: Du musst nicht jedes Detail einer Rede wiedergeben.</p><ol><li><strong>Auftrag markieren:</strong> Welche Aspekte werden verlangt?</li><li><strong>Relevante Gedanken sammeln:</strong> Hauptaussage und zentrale Begründungen auswählen.</li><li><strong>Ordnen und bündeln:</strong> Verwandte Aussagen zusammenfassen.</li><li><strong>Eigenständig formulieren:</strong> Sachlich, knapp und im Präsens schreiben.</li><li><strong>Kontrollieren:</strong> Keine eigene Meinung, keine Analyse, keine erfundenen Informationen.</li></ol><blockquote lang="en">The speaker argues that a gap year can help young people become more independent. However, she stresses that careful planning is essential.</blockquote><p>Ein kurzer Einleitungssatz nennt Redner/in und Thema. Erfinde kein Datum oder Publikum. Anders als bei einer Analyse brauchst du für diese Übungszusammenfassungen keine Zitate; nutze eigene Formulierungen.</p><h3>Useful beginnings</h3><p lang="en">The speaker focuses on …<br>She points out that …<br>Another key idea is …<br>He also stresses the importance of …</p><div class="notice">Merke: „I think the speaker is right“ gehört nicht zu Point out. „The speaker believes …“ gibt dagegen die Position der Rede wieder.</div>`,
analyse:`<h2>Vom sprachlichen Mittel zur Wirkung</h2><p>In eurer Edumap zu Obama stehen direkte Ansprache, Wiederholung/Anapher und Kontrast im Mittelpunkt. Für eine einfache Analyse reichen zwei gut erklärte Beobachtungen.</p><div class="table-scroll"><table><thead><tr><th>Mittel</th><th>Eigenes Beispiel</th><th>Mögliche Wirkung</th></tr></thead><tbody><tr><td>Direct address</td><td lang="en">You can make a difference.</td><td>Bezieht die Zuhörenden persönlich ein.</td></tr><tr><td>Repetition / anaphora</td><td lang="en">We need a plan. We need a purpose.</td><td>Die gleichen Satzanfänge betonen die Anforderungen und geben Rhythmus.</td></tr><tr><td>Contrast</td><td lang="en">A year of learning, not a year of waiting.</td><td>Stellt aktive Entwicklung und Passivität gegenüber.</td></tr><tr><td>Rhetorical question</td><td lang="en">What could you learn beyond the classroom?</td><td>Regt zum Nachdenken über Möglichkeiten an.</td></tr></tbody></table></div><h3>Device → evidence → effect → message</h3><blockquote lang="en">The speaker uses direct address in “You can make a difference” (paragraph 2). This makes the students feel personally involved and supports her call to take responsibility.</blockquote><p>Belege deine Aussage kurz und genau. Erkläre dann die Wirkung <em>dieser Stelle</em> auf <em>dieses Publikum</em>. „It makes the speech interesting“ ist zu allgemein. Schreibe „may encourage“, wenn du eine mögliche Wirkung beschreibst.</p><div class="notice">Anapher bedeutet Wiederholung gleicher Wörter an aufeinanderfolgenden Satz- oder Teilsatzanfängen. Ähnliche Satzstrukturen allein sind Parallelismus. Nicht jede Wiederholung ist eine Anapher.</div><p>Die Gates-Rede in eurer Einheit verbindet konkrete Probleme mit der Frage nach wirksamer Hilfe. Übertrage diese Analyseidee: Wie hilft ein Mittel dabei, die Botschaft der Rede verständlich und überzeugend zu machen?</p>`,
speech:`<h2>Write for people, not just for a page.</h2><p>Eine Rede hat ein Publikum und ein Ziel. Überlege vor dem Schreiben: Wen spreche ich an? Wovon möchte ich überzeugen? Welche Bedenken sollte ich ernst nehmen?</p><ol><li><strong>Opening:</strong> Begrüßung und ein passender Einstieg – zum Beispiel eine Frage.</li><li><strong>Position:</strong> Mache deine Haltung zu Gap Years deutlich.</li><li><strong>Arguments:</strong> Entwickle zwei Argumente mit Begründungen und konkreten Beispielen.</li><li><strong>Counterargument:</strong> Greife einen Einwand fair auf und antworte darauf.</li><li><strong>Ending:</strong> Formuliere einen nachvollziehbaren Appell.</li></ol><blockquote lang="en">Fellow students, a gap year is not automatically a wasted year. But it is not automatically a useful one either. What matters is what we do with it.</blockquote><h3>Useful links</h3><p lang="en">First of all … · For example … · Some people argue that … · This is a real concern. However … · Therefore … · Let us …</p><p>Nutze direkte Ansprache und ein weiteres Mittel, etwa Wiederholung oder Kontrast. Wenige passende Mittel sind besser als viele unverbundene Effekte. Deine Position darf für oder gegen ein Gap Year sein – überzeugend wird sie durch Begründungen.</p><div class="notice">Erfundene Statistiken überzeugen nicht. Nutze nachvollziehbare Beispiele und kennzeichne vorgestellte Situationen mit „Imagine …“.</div>`
};
const q=(prompt,correct,wrong1,wrong2,explanation)=>({prompt,options:[correct,wrong1,wrong2],correct:0,explanation});
export const questions={
gap:[
q('Which statement about a gap year is most accurate?','It can combine work, volunteering and learning.','It must be a year-long holiday abroad.','It guarantees a better job.','Ein Gap Year kann unterschiedlich gestaltet werden. Ein beruflicher Erfolg ist nicht garantiert.'),
q('Which is a realistic benefit of volunteering?','Gaining practical experience and responsibility.','Solving every problem in a community.','Never feeling lonely.','Praktische Erfahrungen und Verantwortung sind realistische Chancen; absolute Versprechen sind es nicht.'),
q('What should a realistic budget include?','Travel, housing, insurance and everyday costs.','Only the plane ticket.','Only money for entertainment.','Zur Planung gehören alle wichtigen Ausgaben, nicht nur die Anreise.'),
q('What does the FSJ Kultur example mainly illustrate?','Practical work can help with career orientation.','All volunteers must become actors.','Cultural work has no everyday routine.','Das Theaterbeispiel zeigt, wie praktische Einblicke berufliche Interessen konkretisieren können.'),
q('Which concern is a strong counterargument?','Not everyone can afford an unpaid placement.','Every gap year is completely pointless.','All volunteers dislike travelling.','Finanzielle Zugänglichkeit ist ein konkreter Einwand. Die anderen Aussagen verallgemeinern unbelegt.'),
q('Which response takes homesickness seriously?','Plan ways to stay in touch and seek support.','Promise that it will never happen.','Treat it as proof of failure.','Heimweh ist eine mögliche Herausforderung. Vorbereitung und Unterstützung helfen, damit umzugehen.'),
q('What matters for responsible volunteering?','Useful tasks that fit local needs and your skills.','Choosing only the best photo opportunities.','Assuming local people need no say.','Ein sinnvoller Beitrag orientiert sich an lokalen Bedürfnissen und realistischen eigenen Fähigkeiten.'),
q('Which conclusion is balanced?','A gap year can help, but purpose and planning matter.','A gap year is always better than university.','Nobody can learn anything during a gap year.','Die erste Aussage wägt Möglichkeiten und Bedingungen ab.'),
q('What belongs to preparation for volunteering abroad?','Checking requirements, responsibilities and support.','Arriving without knowing your tasks.','Assuming all programmes have identical funding.','Paulas Beispiel betont Vorbereitung. Die Bedingungen hängen vom jeweiligen Programm ab.'),
q('Which example supports career orientation?','Trying technical tasks at a theatre before training.','Buying an expensive backpack.','Posting a holiday picture.','Das Beispiel verbindet eine konkrete Tätigkeit mit einer späteren beruflichen Entscheidung.')],
point:[
q('What does “Point out the main ideas” ask you to do?','Present the relevant ideas without commenting.','Judge whether the speaker is a good person.','List every rhetorical device.','Point out verlangt eine gezielte, sachliche Wiedergabe der verlangten Informationen.'),
q('Which sentence fits a point-out response?','The speaker stresses the importance of planning.','I totally agree with the speaker.','The speech is incredibly beautiful.','Die erste Formulierung gibt eine Aussage der Rede wieder; die anderen enthalten eigene Bewertungen.'),
q('How should you handle minor details?','Omit them unless they are relevant to the task.','Include every example and anecdote.','Replace them with invented facts.','Wähle nach dem Aufgabenfokus aus. Vollständigkeit bedeutet nicht, jedes Detail abzuschreiben.'),
q('Which tense usually fits a speech summary?','Present tense.','Future tense only.','Past perfect in every sentence.','Bei der Wiedergabe einer Textaussage ist das Präsens üblich: “The speaker argues …”.'),
q('The task asks for benefits. What should you focus on?','The benefits mentioned by the speaker.','Your own travel plans.','Every detail about the speaker’s life.','Der Operator muss zusammen mit dem konkreten Aufgabenfokus gelesen werden.'),
q('How do you deal with repeated ideas?','Combine them into one clear point.','Repeat them as often as the speaker does.','Delete the main idea entirely.','Eine Zusammenfassung bündelt Wiederholungen und bleibt knapp.'),
q('Which is a useful opening?','In her speech, Maya discusses the value of a planned gap year.','I will now write a very good summary.','This speech was definitely given in London in 2020.','Nenne bekannte Informationen. Erfinde keinen Ort und kein Datum.'),
q('What should you do with the speaker’s wording?','Paraphrase accurately in your own words.','Copy whole paragraphs.','Change the message to your personal view.','Eigenständigkeit bedeutet eigene Formulierungen bei gleichbleibender Aussage.'),
q('Which sentence belongs in analysis rather than point out?','The repeated opening creates a sense of urgency.','The speaker recommends planning ahead.','The speaker mentions financial difficulties.','Eine Erklärung der Wirkung eines Mittels ist Analyse, nicht bloße Inhaltswiedergabe.'),
q('What makes a point-out response coherent?','Grouping related ideas in a logical order.','Writing unrelated keywords only.','Following every sentence of the speech exactly.','Verwandte Aussagen lassen sich zusammenführen. Die Reihenfolge darf sich sinnvoll vom Ausgangstext lösen.')],
analyse:[
q('“You can choose your next step.” Which device is clearest?','Direct address.','Anaphora.','A statistic.','“You” spricht das Publikum unmittelbar an.'),
q('“We need a plan. We need a purpose.” What is repeated?','The opening phrase: anaphora.','The final word: rhyme.','A numerical fact: statistics.','Die identische Wortgruppe “We need” am Satzanfang ist eine Anapher.'),
q('“A year of learning, not a year of waiting.” What is the device?','Contrast.','A quotation from research.','Direct address.','Die Formulierung stellt Lernen und bloßes Warten einander gegenüber.'),
q('Which explanation is most precise?','“You” makes students feel personally responsible.','“You” makes the text nice.','“You” proves that every listener agrees.','Eine Analyse erklärt eine plausible Wirkung auf das konkrete Publikum. Zustimmung ist nicht beweisbar.'),
q('What should follow a short quotation in an analysis?','An explanation of its effect and purpose.','An unrelated personal story.','A list of more devices without comment.','Der Beleg allein genügt nicht. Verbinde ihn mit Wirkung und Botschaft.'),
q('“What could you learn beyond school?” invites reflection. Which device?','Rhetorical question.','Anaphora.','A factual survey result.','Als Rede-Einstieg regt die Frage zum Nachdenken an, statt eine tatsächliche Umfrage durchzuführen.'),
q('Which analysis structure is most useful?','Device, evidence, effect, link to the message.','Opinion, holiday story, goodbye.','Quotation, quotation, quotation.','Nenne das Mittel, belege es und erkläre die Funktion für die Aussage der Rede.'),
q('Why can repetition work well in a speech?','It can emphasise a message and create rhythm.','It always proves an argument is true.','It replaces the need for any content.','Wiederholung betont und strukturiert; sie ist kein Wahrheitsbeweis.'),
q('What makes a contrast useful in a gap-year speech?','It can clarify the difference between drifting and purposeful learning.','It proves every gap year is successful.','It removes all financial problems.','Die Wirkung muss sich auf die konkrete Gegenüberstellung im Text beziehen.'),
q('What is true about anaphora?','It repeats words at the start of successive clauses.','It means every repeated word anywhere in a text.','It means any two sentences have the same length.','Nicht jede Wiederholung ist eine Anapher; die Position am Anfang ist entscheidend.')],
speech:[
q('What should you decide before writing a speech?','Your audience and purpose.','How to include the most difficult words.','How to avoid having a position.','Publikum und Ziel bestimmen Inhalt, Ton und Aufbau.'),
q('Which opening suits a school assembly?','Fellow students, what do you want to learn after school?','Dear Sir or Madam, enclosed please find my application.','Once upon a time, in a distant kingdom …','Die erste Formulierung spricht Mitschülerinnen und Mitschüler direkt an und eröffnet das Thema.'),
q('What makes an argument convincing?','A clear claim, a reason and a relevant example.','A claim repeated without explanation.','A made-up percentage.','Begründung und Beispiel machen eine Position nachvollziehbar.'),
q('How should you handle a counterargument?','Acknowledge it fairly and respond to it.','Ignore every possible concern.','Insult people who disagree.','Ein fair behandelter Einwand macht die eigene Position differenzierter.'),
q('Which ending contains a call to action?','Before you choose, compare options and make a realistic plan.','That is everything I could think of.','This text has exactly five paragraphs.','Ein Appell gibt dem Publikum einen konkreten nächsten Schritt.'),
q('Which linking phrase introduces a counterargument?','Some people argue that …','For example …','First of all …','“Some people argue that” führt eine andere Position ein.'),
q('Which statement uses evidence responsibly?','A theatre placement may help you discover a technical career.','Exactly 97.4% of volunteers become millionaires.','Everybody who stays home fails.','Ein nachvollziehbares Beispiel ist besser als eine erfundene Zahl oder absolute Behauptung.'),
q('Which device creates a memorable ending?','A purposeful repetition of the central message.','An unrelated list of travel destinations.','A sudden change to a different topic.','Eine gezielte Wiederholung kann die Kernbotschaft verankern.'),
q('Can a good speech argue against taking a gap year?','Yes, if the position is clearly justified.','No, only a positive opinion is allowed.','Only if it contains no examples.','Die Qualität der Begründung zählt, nicht die gewünschte Meinung.'),
q('Which sentence connects a concern with a response?','Cost is a real concern. However, local options may be more affordable.','Everyone is wrong. End of story.','There are costs. Anyway, I like beaches.','Die erste Antwort nimmt einen Einwand ernst und reagiert sachlich darauf.')]
};
export const speeches={
maya:{title:'A year with a purpose',speaker:'Maya, student representative',context:'Fiktive Rede bei einer schulischen Informationsveranstaltung. Eigener Übungstext, 2026.',paragraphs:[
'Fellow students, in a few months we will face a question that no timetable can answer: what comes next? Some of us will study, others will start training, and some will consider a gap year. A different path is not automatically a wrong path.',
'You can learn beyond the classroom. You can learn to manage a budget, work in a team and face unfamiliar situations. A placement at a local theatre, for example, might reveal a talent for technical work that you never discovered at school. Practical experience can turn a vague interest into a clearer career choice.',
'But a gap year is not a magic ticket to maturity. Travel, housing and insurance cost money. Being away from familiar people can also be lonely. Some students cannot afford to work without pay. We must take these limits seriously instead of pretending that everyone has the same choices.',
'That is why we need a plan. We need a purpose. We need people who can support us. Before joining a project, ask what work you will actually do, what skills are needed and whom your work will help. A local placement can be as meaningful as a journey across the world.',
'Let us choose a year of learning, not a year of waiting. A gap year is valuable when it helps us grow and lets us contribute responsibly. Do not choose it because it looks exciting online. Choose it because you know what you want to try, what it will cost and what you hope to learn.'
]},
leo:{title:'Do not confuse distance with purpose',speaker:'Leo, former gap-year volunteer',context:'Fiktive Rede vor einer Abschlussklasse. Eigener Übungstext, 2026.',paragraphs:[
'Good morning, everyone. When I left school, I thought a long journey would give me all the answers. I bought a ticket before I had asked a single useful question. What did I want to learn? How would I pay for it? Who would support me if something went wrong?',
'My first weeks were difficult. I spent more than I expected and missed my friends. The photographs looked exciting, but my daily routine felt empty. Distance had changed my surroundings; it had not given me a purpose.',
'Things improved when I joined a community project with clear tasks and a supervisor. I helped organise activities, listened to the team and learned to arrive prepared. The work was sometimes ordinary. Yet it taught me more about responsibility than my most impressive travel photos ever could.',
'I learned to listen. I learned to plan. I learned to ask for help. These are useful lessons, but you do not have to cross an ocean to learn them. Paid work, a local volunteering project or a training course can offer valuable experience too. Staying close to home is not a failure of courage.',
'So, should you take a gap year? Perhaps. But you should not take one simply because your friends do. Check the costs, talk to former participants and find out whether the project actually needs your contribution. Your next step should fit your situation. Choose a purpose first and a destination second.'
]}
};
export const tasks=[
{id:'point-maya',type:'point',title:'01 · The main ideas',speech:'maya',words:'100–140',minutes:15,prompt:'Point out Maya’s main ideas about the benefits and limitations of a gap year and the conditions for making it valuable.',expect:['Praktisches Lernen, Selbstständigkeit und berufliche Orientierung','Kosten, Einsamkeit und ungleiche Möglichkeiten','Klare Ziele, realistische Aufgaben, Finanzierung und Unterstützung','Verantwortlicher Beitrag; auch lokale Angebote sind sinnvoll'],tips:'Ordne deine Antwort nach Chancen, Grenzen und Bedingungen. Schreibe in eigenen Worten und ohne eigene Bewertung.'},
{id:'analysis-maya',type:'analyse',title:'02 · How language persuades',speech:'maya',words:'120–170',minutes:20,prompt:'Analyse how Maya uses direct address and ONE other rhetorical device to encourage students to plan their gap year carefully. Give short quotations and paragraph references, and explain their effects.',expect:['Direkte Ansprache in Absatz 2: persönliche Beteiligung und Verantwortung','Zweites Mittel, z. B. Anapher in Absatz 4 oder Kontrast in Absatz 5','Passende kurze Zitate mit Absatzangaben','Konkrete Wirkung und Bezug zur Botschaft sorgfältiger Planung'],tips:'Schreibe zwei kurze Analyseabsätze. Verwende pro Absatz: Mittel, Beleg, Wirkung und Bezug zur Botschaft.'},
{id:'speech-pro',type:'speech',title:'03 · Your year, your choice',speech:null,words:'220–300',minutes:30,prompt:'Your school is holding a “Life after school” assembly. Write a speech for fellow students explaining whether a gap year is a worthwhile choice. State your position, develop two arguments with examples, respond to one counterargument and end with a call to action. Use direct address and at least one other rhetorical device.',expect:['Klare begründete Position und passende Ansprache von Mitschülern','Zwei entwickelte Argumente mit konkreten Beispielen zu Gap Years','Ein fair behandelter Einwand mit Antwort','Erkennbarer Redeaufbau, gezielte Mittel und passender Schlussappell'],tips:'Du darfst zustimmen, ablehnen oder Bedingungen formulieren. Beispiele aus FSJ Kultur und Freiwilligendienst können helfen; erfinde keine Zahlen.'},
{id:'point-leo',type:'point',title:'04 · Lessons learned',speech:'leo',words:'100–140',minutes:15,prompt:'Point out the difficulties Leo experienced and the lessons he wants school leavers to learn from his gap year.',expect:['Ungeplante Ausgaben, Heimweh und fehlendes Ziel','Strukturierte Mitarbeit und Unterstützung geben Sinn','Zuhören, Planen und Hilfe suchen als Lernerfahrungen','Eigene Situation, Kosten und tatsächlichen Bedarf prüfen; lokale Alternativen'],tips:'Wähle nur Informationen zu Schwierigkeiten und Lehren aus. Erzähle nicht jeden Schritt seiner Reise nach.'},
{id:'analysis-leo',type:'analyse',title:'05 · Make the message memorable',speech:'leo',words:'120–170',minutes:20,prompt:'Analyse how Leo uses repetition in paragraph 4 and ONE contrast elsewhere in the speech to communicate his message about a meaningful gap year. Use short quotations and paragraph references.',expect:['Anapher “I learned” betont zentrale Lernerfahrungen','Kontrast z. B. Fotos versus Alltag (Absatz 2) oder Zweck versus Zielort (Absatz 5)','Präzise Belege mit Absatzangaben','Wirkung auf Schulabgänger und Verbindung zur Botschaft: Sinn vor Entfernung'],tips:'Erkläre, warum das Publikum diese Formulierungen erinnern könnte. Bleibe bei den verlangten zwei Mitteln.'},
{id:'speech-local',type:'speech',title:'06 · Make a difference close to home',speech:null,words:'220–300',minutes:30,prompt:'At your school’s careers evening, some students claim that only a gap year abroad is worth doing. Write a speech responding to this claim. Explain your position using two arguments and concrete examples, take one opposing view seriously and end with a clear recommendation. Address your audience directly and use one further rhetorical device.',expect:['Klare Reaktion auf die These, nur Auslandserfahrungen seien wertvoll','Zwei begründete Argumente und konkrete passende Beispiele','Faire Auseinandersetzung mit einem Vorteil eines Auslandsaufenthalts','Situationsgerechte Rede mit Ansprache, weiterem Mittel und Empfehlung'],tips:'Vergleiche Möglichkeiten, ohne zu behaupten, dass lokale Angebote immer günstiger oder Auslandsangebote immer besser sind.'}
];
export const integrity='Schreibe selbst und ohne KI oder Übersetzungstool. Ein fremd formulierter Text trainiert nicht deine Fähigkeiten für die Klausur am 22.10. Die automatische Rückmeldung hilft dir erst nach deinem eigenen Versuch beim Verbessern.';
