import {GRADING_ENDPOINT} from './config.js';
import {tasks,modules} from './content.js';
const $=id=>document.getElementById(id);let key='',rows=[];
const titles=Object.fromEntries([...tasks,...modules].map(x=>[x.id,x.title]));
const columns=[['Name','name'],['Zugang','codeLabel'],['Datum (UTC)','date'],['Art','kind'],['Aufgabe','taskId'],['Punkte','points'],['Inhalt','content'],['Sprache','language'],['Lexik','lexis'],['Grammatik','grammar'],['Textgestaltung','design'],['Wörter','words'],['Richtig','correct'],['Fragen','total'],['Sekunden/Frage','seconds'],['Bewertung','verification']];
function filtered(){const q=$('filter').value.trim().toLocaleLowerCase('de');return rows.filter(r=>(r.name+' '+(titles[r.taskId]||r.taskId)+' '+r.codeLabel).toLocaleLowerCase('de').includes(q));}
function value(r,k){if(k==='taskId')return titles[r[k]]||r[k];if(k==='kind')return r[k]==='writing'?'Schreiben':'Quiz';if(k==='points')return r.kind==='writing'?r.total:r.points;if(k==='total'&&r.kind==='writing')return '';return r[k]??'';}
function render(){const data=filtered();$('table').replaceChildren();const header=document.createElement('tr');for(const [label] of columns){const th=document.createElement('th');th.textContent=label;th.style.cssText='text-align:left;padding:12px;border-bottom:2px solid #83977c';header.append(th);}$('table').append(header);for(const row of data){const tr=document.createElement('tr');for(const [,k] of columns){const td=document.createElement('td');td.textContent=value(row,k);td.style.cssText='padding:12px;border-bottom:1px solid #ddd;white-space:nowrap';tr.append(td);}$('table').append(tr);}$('count').textContent=data.length+' Ergebnisse';$('export').disabled=!data.length;}
async function load(){if(!key)return;$('status').textContent='Ergebnisse werden geladen …';try{const r=await fetch(GRADING_ENDPOINT.replace(/\/grade$/,'/teacher/results'),{method:'POST',headers:{Authorization:'Bearer '+key},signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Übersicht nicht erreichbar.');rows=data.rows;$('results').hidden=false;$('login').hidden=true;$('teacher-key').value='';render();$('status').textContent='Aktualisiert. Es werden nur die letzten 90 Tage angezeigt.';}catch(e){$('status').textContent=e.message;}}
$('login').onsubmit=e=>{e.preventDefault();key=$('teacher-key').value.trim();load();};$('refresh').onclick=load;$('filter').oninput=render;$('logout').onclick=()=>{key='';rows=[];$('table').replaceChildren();$('results').hidden=true;$('login').hidden=false;$('teacher-key').value='';$('status').textContent='Abgemeldet.';};
export function csvCell(x){let s=String(x??'');if(/^[\s]*[=+@-]/u.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('export').onclick=()=>{const csv='\ufeff'+[columns.map(([l])=>l),...filtered().map(r=>columns.map(([,k])=>value(r,k)))].map(r=>r.map(csvCell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='11BG-Ergebnisse-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
